name: rxn-lm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.8.12
  - pytorch=1.10.2
  - rdkit=2021.09
  - scipy
  - seaborn
  - torchaudio==0.10.2
  - torchvision==0.11.3
  - cudatoolkit=11.3
  - ignite==0.4.10
  - attrs=22.1.0
  - packaging=21.3
  - pytest
  - mkl==2024.0
  - pip:
    - tokenizers==0.11.4
    - tqdm
    - ipdb
    - transformers==4.16.2
    - wandb==0.13.9
    - tabulate
    - aiosignal==1.3.1
    - protobuf==4.24.4
    - grpcio==1.51.1
    - filelock==3.8.0
    - click==8.1.3
    - msgpack==1.0.4
    - ray[tune]==2.2.0
